<h1>Gestion des commentaires</h1>

<p><a href="<?php echo $this->url('admin/comments/add') ?>" class="btn btn-primary">Ajouter un commentaire</a></p>

<table class="table table-striped">
    <thead>
        <tr>
            <th>ID</th>
            <th>Titre</th>
            <th>Catégorie</th>
            <th>Date de publication</th>
            <th>Options</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->posts as $post) : ?>
        <tr>
            <td><?php echo $post->getId() ?></td>
            <td><?php echo $post->getName() ?></td>
            <td><?php echo $post->getCategory()->getName() ?></td>
            <td><?php echo $post->getCreated()->format('d/m/Y H:i') ?></td>
            <td>
                <a href="<?php echo $this->url('admin/posts/edit', array('id' => $post->getId())) ?>" class="btn btn-primary">Modifier</a>
                <a href="<?php echo $this->url('admin/posts/delete', array('id' => $post->getId())) ?>" class="btn btn-danger" onclick="return confirm('Are you sure ?')">Supprimer</a>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<?php
    echo $this->paginationControl(
        $this->posts,
        null,
        'paginator/paginator',
        array('route' => 'admin/posts/list')
    );
?>
