<?php $this->headTitle('Blog') ?>

<div class="page-header">
    <h1>ZenBlog</h1>
    <p class="lead">Bienvenue sur le ZenBlog, un Blog tout en détente.</p>
</div>

<?php if (count($this->posts)) : ?>
    <?php foreach ($this->posts as $post) : ?>
    <article>
        <h2><a href="<?php echo $this->url('posts/show', array('slug' => $post->getSlug())) ?>" title="<?php echo $post->getName() ?>"><?php echo $post->getName() ?></a></h2>
        <p>
            <small>
                Catégorie : <a href="<?php echo $this->url('posts/list', array('category' => $post->getCategory()->getSlug())) ?>"><?php echo $post->getCategory()->getName() ?></a>,
                écrit par <a href="<?php echo $this->url('posts/list', array('author' => $post->getUser()->getId())) ?>"><?php echo $post->getUser()->getUsername() ?></a> le <em><?php echo $post->getCreated()->format('F jS, H:i') ?></em>
            </small>
        </p>
        <p><?php echo $this->truncate($this->markdown($post->getContent()), 450); ?></p>
        <p class="text-right">
            <a href="<?php echo $this->url('posts/show', array('slug' => $post->getSlug())) ?>" class="btn btn-primary">Lire la suite...</a>
        </p>
    </article>
    <hr>
    <?php endforeach; ?>

    <?php
        echo $this->paginationControl(
            $this->posts,
            null,
            'paginator/paginator',
            array('route' => 'posts/list', 'otherParams' => array('category' => $this->category, 'author' => $this->author))
        );
    ?>
<?php else : ?>
    <h3>Il n'y a aucun billet pour le moment</h3>
<?php endif; ?>
