<?php $this->headTitle($this->post->getName()) ?>

<div class="page-header">
    <h1><?php echo $this->post->getName() ?></h1>
    <p>
        <small>
            Catégorie : <a href="<?php echo $this->url('posts/list', array('category' => $this->post->getCategory()->getSlug())) ?>"><?php echo $this->post->getCategory()->getName() ?></a>,
            écrit par <a href="<?php echo $this->url('posts/list', array('author' => $this->post->getUser()->getId())) ?>"><?php echo $this->post->getUser()->getUsername() ?></a> le <em><?php echo $this->post->getCreated()->format('F jS, H:i') ?></em>
        </small>
    </p>
</div>

<article>
    <?php echo $this->markdown($this->post->getContent()); ?>
</article>

<hr>

<section class="comments">

    <h3>Commenter ce billet</h3>

    <?php $this->form->prepare() ?>
    <?php echo $this->form()->openTag($this->form); ?>
    <?php $commentForm = $this->form->get('comment'); ?>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <?php echo $this->formInput($commentForm->get('mail')) ?>
                    <?php echo $this->formElementErrors($commentForm->get('mail')) ?>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <?php echo $this->formInput($commentForm->get('username')) ?>
                    <?php echo $this->formElementErrors($commentForm->get('username')) ?>
                </div>
            </div>
        </div>
        <div class="form-group">
            <?php echo $this->formTextarea($commentForm->get('content')) ?>
            <?php echo $this->formElementErrors($commentForm->get('content')) ?>
        </div>
        <div class="form-group">
            <?php echo $this->formSubmit($this->form->get('submit')) ?>
        </div>

    <?php echo $this->formHidden($this->form->get('csrf_comment')) ?>
    <?php echo $this->form()->closeTag() ?>

    <h3><?php echo count($this->post->getComments()) . ' ' . $this->translatePlural('Commentaire', 'Commentaires', count($this->post->getComments())) ?></h3>

    <?php foreach ($this->post->getComments() as $comment) : ?>
    <div class="row">
        <div class="col-md-2">
            <?php echo $this->gravatar($comment->getMail()); ?>
        </div>
        <div class="col-md-10">
            <p><strong><?php echo $comment->getUsername() ?></strong> <?php echo $this->timeAgo($comment->getCreated()) ?></p>
            <p><?php echo nl2br($comment->getContent()) ?></p>
        </div>
    </div>
    <hr>
    <?php endforeach; ?>
</section>
