<?php $this->headTitle('Admin') ?>

<?php $this->form->prepare() ?>
<?php echo $this->form()->openTag($this->form); ?>

    <h4 class="form-signin-heading">Inscription</h4>
    <?php $userForm = $this->form->get('user'); ?>
    <?php echo $this->formInput($userForm->get('name')) ?>
    <?php echo $this->formInput($userForm->get('fname')) ?>
    <?php echo $this->formInput($userForm->get('email')) ?>
    <?php echo $this->formInput($userForm->get('username')) ?>
    <?php echo $this->formPassword($userForm->get('password')) ?>
    <?php echo $this->formSubmit($this->form->get('submit')) ?>

<?php echo $this->form()->closeTag() ?>
